# .github/workflows/sbs_update.yml

name: SBS Data Extraction

on:
  schedule:
    # Ejecutar todos los lunes a las 00:00 UTC
    # Nota: GitHub Actions usa UTC, Perú está en UTC-5
    # Para que se ejecute a las 00:00 hora de Perú, programa a las 05:00 UTC
    - cron: '0 5 * * 1'
  
  # Permitir ejecución manual desde GitHub
  workflow_dispatch:

jobs:
  extract-and-upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Ajusta a tu versión de Python
    
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Set up GCS credentials
      run: |
        echo '${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}' > gcs-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=gcs-key.json" >> $GITHUB_ENV
    
    - name: Run SBS extraction script
      run: |
        python src/main_sbs.py
    
    - name: Clean up credentials
      if: always()
      run: |
        rm -f gcs-key.json
    
    - name: Upload logs (opcional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: execution-logs
        path: logs/  # Ajusta si tienes logs en otro directorio
        retention-days: 7
